/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

/**
 *
 * @author ahmed
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        login = new javax.swing.JPanel();
        login_buttom = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        forgot_password = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        login_background = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        username1 = new javax.swing.JTextField();
        Password1 = new javax.swing.JPasswordField();
        Password2 = new javax.swing.JPasswordField();
        login_buttom1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 600));
        setMinimumSize(new java.awt.Dimension(400, 600));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(217, 217, 217));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(400, 600));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(400, 650));

        login.setBackground(new java.awt.Color(217, 217, 217));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_buttom.setBackground(new java.awt.Color(0, 138, 188));
        login_buttom.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        login_buttom.setForeground(new java.awt.Color(237, 231, 227));
        login_buttom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_buttom.setText("Login");
        login_buttom.setOpaque(true);
        login.add(login_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 170, 30));

        register.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        register.setForeground(new java.awt.Color(0, 138, 188));
        register.setText("Register now");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        login.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, 30));

        forgot_password.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        forgot_password.setForeground(new java.awt.Color(106, 106, 106));
        forgot_password.setText("Forgot pasword?");
        login.add(forgot_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 120, 30));

        username.setBackground(new java.awt.Color(217, 217, 217));
        username.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        username.setForeground(new java.awt.Color(0, 138, 188));
        username.setToolTipText("Enter your name");
        username.setBorder(null);
        username.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 219, 180, 40));

        Password.setBackground(new java.awt.Color(217, 217, 217));
        Password.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 138, 188));
        Password.setToolTipText("Enter your password");
        Password.setBorder(null);
        login.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 310, 180, 30));

        login_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Login (1).png"))); // NOI18N
        login.add(login_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab1", login);

        Register.setBackground(new java.awt.Color(217, 217, 217));
        Register.setMaximumSize(new java.awt.Dimension(400, 600));
        Register.setMinimumSize(new java.awt.Dimension(400, 600));
        Register.setPreferredSize(new java.awt.Dimension(400, 600));
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username1.setBackground(new java.awt.Color(217, 217, 217));
        username1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        username1.setForeground(new java.awt.Color(0, 138, 188));
        username1.setToolTipText("Enter your name");
        username1.setBorder(null);
        username1.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        Register.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 219, 180, 40));

        Password1.setBackground(new java.awt.Color(217, 217, 217));
        Password1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Password1.setForeground(new java.awt.Color(0, 138, 188));
        Password1.setToolTipText("Enter your password");
        Password1.setBorder(null);
        Register.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 180, 40));

        Password2.setBackground(new java.awt.Color(217, 217, 217));
        Password2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Password2.setForeground(new java.awt.Color(0, 138, 188));
        Password2.setToolTipText("Enter your password");
        Password2.setBorder(null);
        Register.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 320, 180, 30));

        login_buttom1.setBackground(new java.awt.Color(0, 138, 188));
        login_buttom1.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        login_buttom1.setForeground(new java.awt.Color(237, 231, 227));
        login_buttom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_buttom1.setText("Register");
        login_buttom1.setOpaque(true);
        Register.add(login_buttom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Register (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Register.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jTabbedPane1.addTab("tab2", Register);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel forgot_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel login;
    private javax.swing.JLabel login_background;
    private javax.swing.JLabel login_buttom;
    private javax.swing.JLabel login_buttom1;
    private javax.swing.JLabel register;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
