/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills_management_system;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.UIManager;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author mariam
 */
public class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        initComponents();
    }

    public void showPieChart() {
    } /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    
    // Colors  global variables
    private int Choose = 1;
    Color blue = Color.decode("#008ABC");
    Color gray = Color.decode("#6A6A6A");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrickeyPanel = new javax.swing.JPanel();
        UserName = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        NavDashboard = new javax.swing.JLabel();
        NavBills = new javax.swing.JLabel();
        NavSettings = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        NunberOfComplaints = new javax.swing.JLabel();
        ComplaintsNumberCard = new javax.swing.JLabel();
        TotalSolvedComplaints = new javax.swing.JLabel();
        TotalSolvedComplaintsCard = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DashboardTable = new javax.swing.JTable();
        panelBarChart = new javax.swing.JPanel();
        Archieve = new javax.swing.JLabel();
        Bills = new javax.swing.JPanel();
        NumberOfBills = new javax.swing.JLabel();
        TotalCostOfBills = new javax.swing.JLabel();
        TotalNumberOfBillsCard = new javax.swing.JLabel();
        TotalCostOfBillsCard = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillsTable = new javax.swing.JTable();
        Settings = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TrickeyPanel.setBackground(new java.awt.Color(0, 176, 239));
        getContentPane().add(TrickeyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 920, 1320, 50));

        UserName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        UserName.setForeground(new java.awt.Color(17, 43, 60));
        UserName.setText("USER");
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 90, 120, 50));

        NavBar.setOpaque(false);
        NavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NavDashboard.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        NavDashboard.setForeground(new java.awt.Color(0, 138, 188));
        NavDashboard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NavDashboard.setText("Dashboard");
        NavDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavDashboardMouseExited(evt);
            }
        });
        NavBar.add(NavDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 40));

        NavBills.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        NavBills.setForeground(new java.awt.Color(106, 106, 106));
        NavBills.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NavBills.setText("Bills");
        NavBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavBillsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavBillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavBillsMouseExited(evt);
            }
        });
        NavBar.add(NavBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 50, -1));

        NavSettings.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        NavSettings.setForeground(new java.awt.Color(106, 106, 106));
        NavSettings.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NavSettings.setText("Settings");
        NavSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavSettingsMouseExited(evt);
            }
        });
        NavBar.add(NavSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 140, 50));

        getContentPane().add(NavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 1300, 70));

        jTabbedPane1.setBackground(new java.awt.Color(217, 217, 217));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1320, 750));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1320, 750));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1320, 750));

        Dashboard.setBackground(new java.awt.Color(217, 217, 217));
        Dashboard.setMaximumSize(new java.awt.Dimension(1320, 750));
        Dashboard.setMinimumSize(new java.awt.Dimension(1320, 750));
        Dashboard.setOpaque(false);
        Dashboard.setPreferredSize(new java.awt.Dimension(1320, 750));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NunberOfComplaints.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        NunberOfComplaints.setForeground(new java.awt.Color(51, 255, 51));
        NunberOfComplaints.setText("NO.");
        Dashboard.add(NunberOfComplaints, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 100, 60));

        ComplaintsNumberCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Admin/Number of complaints.png"))); // NOI18N
        Dashboard.add(ComplaintsNumberCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 490, -1));

        TotalSolvedComplaints.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        TotalSolvedComplaints.setForeground(new java.awt.Color(51, 255, 51));
        TotalSolvedComplaints.setText("NO.");
        Dashboard.add(TotalSolvedComplaints, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 90, 60));

        TotalSolvedComplaintsCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Admin/solved complaints.png"))); // NOI18N
        Dashboard.add(TotalSolvedComplaintsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 520, -1));

        SearchTextField.setBackground(new java.awt.Color(255, 255, 255));
        SearchTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(0, 138, 188));
        SearchTextField.setBorder(null);
        Dashboard.add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 400, 40));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Admin/Search.png"))); // NOI18N
        Dashboard.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        DashboardTable.setBackground(new java.awt.Color(51, 51, 55));
        DashboardTable.setForeground(new java.awt.Color(255, 255, 255));
        DashboardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DashboardTable.setPreferredSize(new java.awt.Dimension(535, 1320));
        DashboardTable.setRowHeight(35);
        DashboardTable.setSelectionBackground(new java.awt.Color(228, 238, 242));
        DashboardTable.setSelectionForeground(new java.awt.Color(51, 51, 55));
        jScrollPane1.setViewportView(DashboardTable);

        Dashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 1220, 260));

        panelBarChart.setBackground(new java.awt.Color(50, 50, 50));
        panelBarChart.setForeground(new java.awt.Color(217, 217, 217));
        panelBarChart.setPreferredSize(new java.awt.Dimension(540, 346));
        panelBarChart.setLayout(new java.awt.BorderLayout());
        Dashboard.add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 270, 200));

        Archieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Admin/Archieve.png"))); // NOI18N
        Dashboard.add(Archieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, -1, -1));

        jTabbedPane1.addTab("tab1", Dashboard);

        Bills.setMaximumSize(new java.awt.Dimension(1320, 750));
        Bills.setMinimumSize(new java.awt.Dimension(1320, 750));
        Bills.setOpaque(false);
        Bills.setPreferredSize(new java.awt.Dimension(1320, 750));
        Bills.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumberOfBills.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        NumberOfBills.setForeground(new java.awt.Color(51, 255, 51));
        NumberOfBills.setText("NO.");
        Bills.add(NumberOfBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, 60));

        TotalCostOfBills.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        TotalCostOfBills.setForeground(new java.awt.Color(51, 255, 51));
        TotalCostOfBills.setText("NO.");
        Bills.add(TotalCostOfBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 90, 60));

        TotalNumberOfBillsCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Number of bills card.png"))); // NOI18N
        Bills.add(TotalNumberOfBillsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 490, -1));

        TotalCostOfBillsCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Total cost card.png"))); // NOI18N
        Bills.add(TotalCostOfBillsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 520, -1));

        BillsTable.setBackground(new java.awt.Color(51, 51, 55));
        BillsTable.setForeground(new java.awt.Color(255, 255, 255));
        BillsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BillsTable.setPreferredSize(new java.awt.Dimension(535, 1320));
        BillsTable.setRowHeight(35);
        BillsTable.setSelectionBackground(new java.awt.Color(228, 238, 242));
        BillsTable.setSelectionForeground(new java.awt.Color(51, 51, 55));
        jScrollPane2.setViewportView(BillsTable);

        Bills.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 1230, 350));

        jTabbedPane1.addTab("tab4", Bills);

        Settings.setMaximumSize(new java.awt.Dimension(1320, 750));
        Settings.setMinimumSize(new java.awt.Dimension(1320, 750));
        Settings.setOpaque(false);
        Settings.setPreferredSize(new java.awt.Dimension(1320, 750));
        jTabbedPane1.addTab("tab2", Settings);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Admin/Dashboard Admin.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1496, 1032));
        background.setMinimumSize(new java.awt.Dimension(1496, 1032));
        background.setPreferredSize(new java.awt.Dimension(1496, 1032));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NavDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavDashboardMouseClicked
        // TODO add your handling code here:
        Choose = 1;
        jTabbedPane1.setSelectedIndex(0);
        NavDashboard.setForeground(blue);
        NavBills.setForeground(gray);
        NavSettings.setForeground(gray);
        NavDashboard.setText("Dashboard");
    }//GEN-LAST:event_NavDashboardMouseClicked

    private void NavDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavDashboardMouseEntered

        if (Choose == 1) {
        } else {
            String underline = "<HTML><u>Dashboard</u></HTML>";
            NavDashboard.setText(underline);
        }
    }//GEN-LAST:event_NavDashboardMouseEntered

    private void NavDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavDashboardMouseExited

        NavDashboard.setText("Dashboard");
    }//GEN-LAST:event_NavDashboardMouseExited

    private void NavBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavBillsMouseClicked

        Choose = 2;
        jTabbedPane1.setSelectedIndex(1);
        NavBills.setForeground(blue);
        NavDashboard.setForeground(gray);
        NavSettings.setForeground(gray);
        NavBills.setText("Bills");
    }//GEN-LAST:event_NavBillsMouseClicked

    private void NavBillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavBillsMouseEntered

        if (Choose == 2) {
        } else {
            String underline = "<HTML><u>Bills</u></HTML>";
            NavBills.setText(underline);
        }
    }//GEN-LAST:event_NavBillsMouseEntered

    private void NavBillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavBillsMouseExited

        NavBills.setText("Bills");
    }//GEN-LAST:event_NavBillsMouseExited

    private void NavSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavSettingsMouseClicked

        Choose = 3;

        jTabbedPane1.setSelectedIndex(2);
        NavDashboard.setForeground(gray);
        NavBills.setForeground(gray);
        NavSettings.setForeground(blue);
        NavSettings.setText("Settings");
    }//GEN-LAST:event_NavSettingsMouseClicked

    private void NavSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavSettingsMouseEntered

        if (Choose == 3) {
        } else {
            String underline = "<HTML><u>Settings</u></HTML>";
            NavSettings.setText(underline);

        }
    }//GEN-LAST:event_NavSettingsMouseEntered

    private void NavSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavSettingsMouseExited

        NavSettings.setText("Settings");
    }//GEN-LAST:event_NavSettingsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Archieve;
    private javax.swing.JPanel Bills;
    private javax.swing.JTable BillsTable;
    private javax.swing.JLabel ComplaintsNumberCard;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JTable DashboardTable;
    private javax.swing.JPanel NavBar;
    private javax.swing.JLabel NavBills;
    private javax.swing.JLabel NavDashboard;
    private javax.swing.JLabel NavSettings;
    private javax.swing.JLabel NumberOfBills;
    private javax.swing.JLabel NunberOfComplaints;
    private javax.swing.JLabel Search;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JPanel Settings;
    private javax.swing.JLabel TotalCostOfBills;
    private javax.swing.JLabel TotalCostOfBillsCard;
    private javax.swing.JLabel TotalNumberOfBillsCard;
    private javax.swing.JLabel TotalSolvedComplaints;
    private javax.swing.JLabel TotalSolvedComplaintsCard;
    private javax.swing.JPanel TrickeyPanel;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
