/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills_management_system;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author mariam
 */
public class ChangePasswordCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CustomerSettings
     */
    public ChangePasswordCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bachground = new javax.swing.JPanel();
        NewPassword = new javax.swing.JTextField();
        SaveButton = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bachground.setMaximumSize(new java.awt.Dimension(700, 700));
        Bachground.setMinimumSize(new java.awt.Dimension(700, 700));
        Bachground.setPreferredSize(new java.awt.Dimension(700, 700));
        Bachground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewPassword.setBackground(new java.awt.Color(255, 255, 255));
        NewPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        NewPassword.setForeground(new java.awt.Color(0, 138, 188));
        NewPassword.setBorder(null);
        Bachground.add(NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 240, 40));

        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveButtonMouseEntered(evt);
            }
        });
        Bachground.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 120, 50));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Change Password.png"))); // NOI18N
        Bachground.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Bachground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonMouseEntered

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        
        this.dispose();
    }//GEN-LAST:event_SaveButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try
        {
            UIManager.setLookAndFeel(new FlatLightLaf());

        }
        catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bachground;
    private javax.swing.JLabel Background2;
    private javax.swing.JTextField NewPassword;
    private javax.swing.JLabel SaveButton;
    // End of variables declaration//GEN-END:variables
}
