/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills_management_system;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author mariam
 */
public class CreditCardCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CreditCardCustomer
     */
    public CreditCardCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CardHolderName = new javax.swing.JTextField();
        Pan = new javax.swing.JTextField();
        ExpirationDate = new com.toedter.calendar.JDateChooser();
        AddButton = new javax.swing.JLabel();
        DefaultCard = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CardHolderName.setBackground(new java.awt.Color(255, 255, 255));
        CardHolderName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CardHolderName.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderName.setBorder(null);
        jPanel1.add(CardHolderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 240, 40));

        Pan.setBackground(new java.awt.Color(255, 255, 255));
        Pan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Pan.setForeground(new java.awt.Color(0, 138, 188));
        Pan.setBorder(null);
        jPanel1.add(Pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 240, 40));
        jPanel1.add(ExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 280, 50));
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 130, 50));

        DefaultCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DefaultCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultCardActionPerformed(evt);
            }
        });
        jPanel1.add(DefaultCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Admin/Settings/Done.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Credit Card.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefaultCardActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try
        {
            UIManager.setLookAndFeel(new FlatLightLaf());

        }
        catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddButton;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField CardHolderName;
    private javax.swing.JComboBox<String> DefaultCard;
    private com.toedter.calendar.JDateChooser ExpirationDate;
    private javax.swing.JTextField Pan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
