/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills_management_system;

import java.awt.Color;

/**
 *
 * @author ahmed
 */
public class cusrtomer extends javax.swing.JFrame {
    // Colors  global variables

    private int choose = 1;
    Color blue = Color.decode("#008ABC");
    Color gray = Color.decode("#6A6A6A");

    /**
     * Creates new form login
     */
    public cusrtomer() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        just_a_panel = new javax.swing.JPanel();
        User_Name = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        nav_Dashboard = new javax.swing.JLabel();
        nav_Bills = new javax.swing.JLabel();
        nav_Accounts = new javax.swing.JLabel();
        nav_Settings = new javax.swing.JLabel();
        Billls_icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        total_coast = new javax.swing.JLabel();
        no_tobe_paid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dashboard_table = new javax.swing.JTable();
        total_coast_card = new javax.swing.JLabel();
        total_no_bill_card = new javax.swing.JLabel();
        Bills = new javax.swing.JPanel();
        total_coast_bills = new javax.swing.JLabel();
        no_tobe_paid_bills = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dashboard_table1 = new javax.swing.JTable();
        total_coast_card_bills = new javax.swing.JLabel();
        total_no_bill_card_bills = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        settings = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        Dashboard_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1420, 1024));
        setMinimumSize(new java.awt.Dimension(1420, 1024));
        setPreferredSize(new java.awt.Dimension(1420, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        just_a_panel.setBackground(new java.awt.Color(0, 176, 239));
        getContentPane().add(just_a_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 940, 1320, 30));

        User_Name.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        User_Name.setForeground(new java.awt.Color(17, 43, 60));
        User_Name.setText("USER");
        getContentPane().add(User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 90, 160, 50));

        navbar.setOpaque(false);
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav_Dashboard.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nav_Dashboard.setForeground(new java.awt.Color(0, 138, 188));
        nav_Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nav_Dashboard.setText("Dashboard");
        nav_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_DashboardMouseExited(evt);
            }
        });
        navbar.add(nav_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, 40));

        nav_Bills.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nav_Bills.setForeground(new java.awt.Color(106, 106, 106));
        nav_Bills.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nav_Bills.setText("Bills");
        nav_Bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_BillsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_BillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_BillsMouseExited(evt);
            }
        });
        navbar.add(nav_Bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 90, 40));

        nav_Accounts.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nav_Accounts.setForeground(new java.awt.Color(106, 106, 106));
        nav_Accounts.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nav_Accounts.setText("Accounts");
        nav_Accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_AccountsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_AccountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_AccountsMouseExited(evt);
            }
        });
        navbar.add(nav_Accounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 150, 40));

        nav_Settings.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nav_Settings.setForeground(new java.awt.Color(106, 106, 106));
        nav_Settings.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nav_Settings.setText("Settings");
        nav_Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_SettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_SettingsMouseExited(evt);
            }
        });
        navbar.add(nav_Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 140, 60));
        navbar.add(Billls_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 40, 50));
        navbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 30, 40));

        getContentPane().add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 1300, 70));

        jTabbedPane1.setBackground(new java.awt.Color(217, 217, 217));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(400, 600));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(400, 650));

        Dashboard.setBackground(new java.awt.Color(217, 217, 217));
        Dashboard.setOpaque(false);
        Dashboard.setPreferredSize(new java.awt.Dimension(1318, 723));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_coast.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        total_coast.setForeground(new java.awt.Color(51, 255, 51));
        total_coast.setText("NO.");
        Dashboard.add(total_coast, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, 60));

        no_tobe_paid.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        no_tobe_paid.setForeground(new java.awt.Color(51, 255, 51));
        no_tobe_paid.setText("NO.");
        Dashboard.add(no_tobe_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 90, 60));

        Dashboard_table.setBackground(new java.awt.Color(228, 238, 242));
        Dashboard_table.setForeground(new java.awt.Color(0, 138, 188));
        Dashboard_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Dashboard_table.setPreferredSize(new java.awt.Dimension(535, 1320));
        Dashboard_table.setRowHeight(35);
        jScrollPane1.setViewportView(Dashboard_table);

        Dashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 1230, 350));

        total_coast_card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Number of bills card.png"))); // NOI18N
        Dashboard.add(total_coast_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 490, -1));

        total_no_bill_card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Total cost card.png"))); // NOI18N
        Dashboard.add(total_no_bill_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 520, -1));

        jTabbedPane1.addTab("tab1", Dashboard);

        Bills.setOpaque(false);
        Bills.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_coast_bills.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        total_coast_bills.setForeground(new java.awt.Color(51, 255, 51));
        total_coast_bills.setText("NO.");
        Bills.add(total_coast_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, 60));

        no_tobe_paid_bills.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        no_tobe_paid_bills.setForeground(new java.awt.Color(51, 255, 51));
        no_tobe_paid_bills.setText("NO.");
        Bills.add(no_tobe_paid_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 90, 60));

        Dashboard_table1.setBackground(new java.awt.Color(228, 238, 242));
        Dashboard_table1.setForeground(new java.awt.Color(0, 138, 188));
        Dashboard_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Dashboard_table1.setPreferredSize(new java.awt.Dimension(535, 1320));
        Dashboard_table1.setRowHeight(35);
        jScrollPane2.setViewportView(Dashboard_table1);

        Bills.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 1230, 350));

        total_coast_card_bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Number of bills card.png"))); // NOI18N
        Bills.add(total_coast_card_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 490, -1));

        total_no_bill_card_bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Total cost card.png"))); // NOI18N
        Bills.add(total_no_bill_card_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 520, -1));

        jTabbedPane1.addTab("tab4", Bills);

        account.setOpaque(false);
        jTabbedPane1.addTab("tab5", account);

        settings.setOpaque(false);
        jTabbedPane1.addTab("tab2", settings);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1320, 750));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Dashboard Customer (2).png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1500, -1));
        getContentPane().add(Dashboard_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 40, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav_BillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_BillsMouseClicked
        // TODO add your handling code here:
        choose = 2;
        jTabbedPane1.setSelectedIndex(1);
        nav_Bills.setForeground(blue);
        nav_Dashboard.setForeground(gray);
        nav_Accounts.setForeground(gray);
        nav_Settings.setForeground(gray);
        nav_Bills.setText("Bills");

    }//GEN-LAST:event_nav_BillsMouseClicked

    private void nav_BillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_BillsMouseEntered
        // TODO add your handling code here:
        if (choose == 2) {
        } else {
            String underline = "<HTML><u>Bills</u></HTML>";
            nav_Bills.setText(underline);
        }
    }//GEN-LAST:event_nav_BillsMouseEntered

    private void nav_BillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_BillsMouseExited
        // TODO add your handling code here:
        nav_Bills.setText("Bills");
    }//GEN-LAST:event_nav_BillsMouseExited

    private void nav_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_DashboardMouseClicked
        // TODO add your handling code here:
        choose = 1;
        jTabbedPane1.setSelectedIndex(0);
        nav_Dashboard.setForeground(blue);
        nav_Bills.setForeground(gray);
        nav_Accounts.setForeground(gray);
        nav_Settings.setForeground(gray);
        nav_Dashboard.setText("Dashboard");

    }//GEN-LAST:event_nav_DashboardMouseClicked

    private void nav_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_DashboardMouseEntered
        // TODO add your handling code here:
        if (choose == 1) {
        } else {
            String underline = "<HTML><u>Dashboard</u></HTML>";
            nav_Dashboard.setText(underline);
        }

    }//GEN-LAST:event_nav_DashboardMouseEntered

    private void nav_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_DashboardMouseExited
        // TODO add your handling code here:
        nav_Dashboard.setText("Dashboard");
    }//GEN-LAST:event_nav_DashboardMouseExited

    private void nav_AccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_AccountsMouseClicked
        // TODO add your handling code here:
        choose = 3;
        jTabbedPane1.setSelectedIndex(2);
        nav_Dashboard.setForeground(gray);
        nav_Bills.setForeground(gray);
        nav_Accounts.setForeground(blue);
        nav_Settings.setForeground(gray);
        nav_Accounts.setText("Accounts");

    }//GEN-LAST:event_nav_AccountsMouseClicked

    private void nav_AccountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_AccountsMouseEntered
        // TODO add your handling code here:
        if (choose == 3) {
        } else {
            String underline = "<HTML><u>Accounts</u></HTML>";
            nav_Accounts.setText(underline);

        }
    }//GEN-LAST:event_nav_AccountsMouseEntered

    private void nav_AccountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_AccountsMouseExited
        // TODO add your handling code here:
        nav_Accounts.setText("Accounts");

    }//GEN-LAST:event_nav_AccountsMouseExited

    private void nav_SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_SettingsMouseClicked
        // TODO add your handling code here:
        choose = 4;
        
        jTabbedPane1.setSelectedIndex(3);
        nav_Dashboard.setForeground(gray);
        nav_Bills.setForeground(gray);
        nav_Accounts.setForeground(gray);
        nav_Settings.setForeground(blue);
        nav_Settings.setText("Settings");

    }//GEN-LAST:event_nav_SettingsMouseClicked

    private void nav_SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_SettingsMouseEntered
        // TODO add your handling code here:
        if (choose == 4) {
        } else {
            String underline = "<HTML><u>Settings</u></HTML>";
            nav_Settings.setText(underline);

        }

    }//GEN-LAST:event_nav_SettingsMouseEntered

    private void nav_SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_SettingsMouseExited
        // TODO add your handling code here:
        nav_Settings.setText("Settings");

    }//GEN-LAST:event_nav_SettingsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cusrtomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cusrtomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cusrtomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cusrtomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cusrtomer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Billls_icon;
    private javax.swing.JPanel Bills;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel Dashboard_icon;
    private javax.swing.JTable Dashboard_table;
    private javax.swing.JTable Dashboard_table1;
    private javax.swing.JLabel User_Name;
    private javax.swing.JPanel account;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel just_a_panel;
    private javax.swing.JLabel nav_Accounts;
    private javax.swing.JLabel nav_Bills;
    private javax.swing.JLabel nav_Dashboard;
    private javax.swing.JLabel nav_Settings;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel no_tobe_paid;
    private javax.swing.JLabel no_tobe_paid_bills;
    private javax.swing.JPanel settings;
    private javax.swing.JLabel total_coast;
    private javax.swing.JLabel total_coast_bills;
    private javax.swing.JLabel total_coast_card;
    private javax.swing.JLabel total_coast_card_bills;
    private javax.swing.JLabel total_no_bill_card;
    private javax.swing.JLabel total_no_bill_card_bills;
    // End of variables declaration//GEN-END:variables
}