/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills_management_system;

import static Bills_management_system.Customer.choose2;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;

/**
 *
 * @author ahmed
 */
public class ViewCards extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public ViewCards() {
        initComponents();
    jTabbedPane1.setSelectedIndex(choose2);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MobileView = new javax.swing.JPanel();
        AccountNameMO = new javax.swing.JLabel();
        CardHolderMO = new javax.swing.JLabel();
        PanTEMO = new javax.swing.JLabel();
        ExpirationDateMO = new javax.swing.JLabel();
        CompanyNameMO = new javax.swing.JLabel();
        TelephoneNumbMO = new javax.swing.JLabel();
        ServiceProvoiderMO = new javax.swing.JLabel();
        ChangePaymentCard = new javax.swing.JLabel();
        Donebutton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Waterview = new javax.swing.JPanel();
        AccountNamedW = new javax.swing.JLabel();
        CardHolderW = new javax.swing.JLabel();
        PanW = new javax.swing.JLabel();
        ExpirationDateW = new javax.swing.JLabel();
        CompanyNameW = new javax.swing.JLabel();
        PaymentCodeW = new javax.swing.JLabel();
        CounterCodeW = new javax.swing.JLabel();
        ChangePaymentCard1 = new javax.swing.JLabel();
        Donebutton1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Gasview = new javax.swing.JPanel();
        AccountNamedGas = new javax.swing.JLabel();
        CardHolderGas = new javax.swing.JLabel();
        PanGas = new javax.swing.JLabel();
        ExpirationDateGas = new javax.swing.JLabel();
        CompanyNameGas = new javax.swing.JLabel();
        PaymentCodeGas = new javax.swing.JLabel();
        CounterCodegas = new javax.swing.JLabel();
        ChangePaymentCard2 = new javax.swing.JLabel();
        Donebutton2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Drinkingwater = new javax.swing.JPanel();
        AccountNameDW = new javax.swing.JLabel();
        CardHolderDW = new javax.swing.JLabel();
        PanDW = new javax.swing.JLabel();
        ExpirationDateDW = new javax.swing.JLabel();
        CompanyNameDW = new javax.swing.JLabel();
        QuantityDW = new javax.swing.JLabel();
        ChangePaymentCard3 = new javax.swing.JLabel();
        Donebutton3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Internet = new javax.swing.JPanel();
        AccountNameNET = new javax.swing.JLabel();
        CardHolderNET = new javax.swing.JLabel();
        PanNET = new javax.swing.JLabel();
        ExpirationDateNET = new javax.swing.JLabel();
        CompanyNameNET = new javax.swing.JLabel();
        TelephoneNumbNET = new javax.swing.JLabel();
        ChangePaymentCard4 = new javax.swing.JLabel();
        Donebutton4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Telephone = new javax.swing.JPanel();
        AccountNameTEL = new javax.swing.JLabel();
        CardHolderTEL = new javax.swing.JLabel();
        PanTEL = new javax.swing.JLabel();
        ExpirationDateTEL = new javax.swing.JLabel();
        CompanyNameTEL = new javax.swing.JLabel();
        TelephoneNumbTEL = new javax.swing.JLabel();
        ChangePaymentCard5 = new javax.swing.JLabel();
        Donebutton5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 630));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(217, 217, 217));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(400, 600));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(400, 650));

        MobileView.setBackground(new java.awt.Color(217, 217, 217));
        MobileView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountNameMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AccountNameMO.setForeground(new java.awt.Color(0, 138, 188));
        AccountNameMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(AccountNameMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 270, 40));

        CardHolderMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CardHolderMO.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(CardHolderMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 270, 40));

        PanTEMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PanTEMO.setForeground(new java.awt.Color(0, 138, 188));
        PanTEMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(PanTEMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 270, 40));

        ExpirationDateMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ExpirationDateMO.setForeground(new java.awt.Color(0, 138, 188));
        ExpirationDateMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(ExpirationDateMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 270, 40));

        CompanyNameMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CompanyNameMO.setForeground(new java.awt.Color(0, 138, 188));
        CompanyNameMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(CompanyNameMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 270, 40));

        TelephoneNumbMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TelephoneNumbMO.setForeground(new java.awt.Color(0, 138, 188));
        TelephoneNumbMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(TelephoneNumbMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 270, 40));

        ServiceProvoiderMO.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ServiceProvoiderMO.setForeground(new java.awt.Color(0, 138, 188));
        ServiceProvoiderMO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MobileView.add(ServiceProvoiderMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 270, 40));

        ChangePaymentCard.setText("jLabel3");
        ChangePaymentCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePaymentCardMouseClicked(evt);
            }
        });
        MobileView.add(ChangePaymentCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 610, 290, 50));

        Donebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonebuttonMouseClicked(evt);
            }
        });
        MobileView.add(Donebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Mobile view (1).png"))); // NOI18N
        MobileView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        jTabbedPane1.addTab("tab1", MobileView);

        Waterview.setBackground(new java.awt.Color(217, 217, 217));
        Waterview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountNamedW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AccountNamedW.setForeground(new java.awt.Color(0, 138, 188));
        AccountNamedW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(AccountNamedW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 270, 40));

        CardHolderW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CardHolderW.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(CardHolderW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 270, 40));

        PanW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PanW.setForeground(new java.awt.Color(0, 138, 188));
        PanW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(PanW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 270, 40));

        ExpirationDateW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ExpirationDateW.setForeground(new java.awt.Color(0, 138, 188));
        ExpirationDateW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(ExpirationDateW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 270, 40));

        CompanyNameW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CompanyNameW.setForeground(new java.awt.Color(0, 138, 188));
        CompanyNameW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(CompanyNameW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 270, 40));

        PaymentCodeW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PaymentCodeW.setForeground(new java.awt.Color(0, 138, 188));
        PaymentCodeW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(PaymentCodeW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 270, 40));

        CounterCodeW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CounterCodeW.setForeground(new java.awt.Color(0, 138, 188));
        CounterCodeW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Waterview.add(CounterCodeW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 270, 40));

        ChangePaymentCard1.setText("jLabel3");
        ChangePaymentCard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePaymentCard1MouseClicked(evt);
            }
        });
        Waterview.add(ChangePaymentCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 610, 290, 50));

        Donebutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Donebutton1MouseClicked(evt);
            }
        });
        Waterview.add(Donebutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Water view (1).png"))); // NOI18N
        Waterview.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        jTabbedPane1.addTab("tab1", Waterview);

        Gasview.setBackground(new java.awt.Color(217, 217, 217));
        Gasview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountNamedGas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AccountNamedGas.setForeground(new java.awt.Color(0, 138, 188));
        AccountNamedGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(AccountNamedGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 270, 40));

        CardHolderGas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CardHolderGas.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(CardHolderGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 270, 40));

        PanGas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PanGas.setForeground(new java.awt.Color(0, 138, 188));
        PanGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(PanGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 270, 40));

        ExpirationDateGas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ExpirationDateGas.setForeground(new java.awt.Color(0, 138, 188));
        ExpirationDateGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(ExpirationDateGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 270, 40));

        CompanyNameGas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CompanyNameGas.setForeground(new java.awt.Color(0, 138, 188));
        CompanyNameGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(CompanyNameGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 270, 40));

        PaymentCodeGas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PaymentCodeGas.setForeground(new java.awt.Color(0, 138, 188));
        PaymentCodeGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(PaymentCodeGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 270, 40));

        CounterCodegas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CounterCodegas.setForeground(new java.awt.Color(0, 138, 188));
        CounterCodegas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gasview.add(CounterCodegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 270, 40));

        ChangePaymentCard2.setText("jLabel3");
        ChangePaymentCard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePaymentCard2MouseClicked(evt);
            }
        });
        Gasview.add(ChangePaymentCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 290, 50));

        Donebutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Donebutton2MouseClicked(evt);
            }
        });
        Gasview.add(Donebutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 130, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Gas view (1).png"))); // NOI18N
        Gasview.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        jTabbedPane1.addTab("tab1", Gasview);

        Drinkingwater.setBackground(new java.awt.Color(217, 217, 217));
        Drinkingwater.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountNameDW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AccountNameDW.setForeground(new java.awt.Color(0, 138, 188));
        AccountNameDW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinkingwater.add(AccountNameDW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 270, 40));

        CardHolderDW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CardHolderDW.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderDW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinkingwater.add(CardHolderDW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 270, 40));

        PanDW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PanDW.setForeground(new java.awt.Color(0, 138, 188));
        PanDW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinkingwater.add(PanDW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 270, 40));

        ExpirationDateDW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ExpirationDateDW.setForeground(new java.awt.Color(0, 138, 188));
        ExpirationDateDW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinkingwater.add(ExpirationDateDW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 270, 40));

        CompanyNameDW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CompanyNameDW.setForeground(new java.awt.Color(0, 138, 188));
        CompanyNameDW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinkingwater.add(CompanyNameDW, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 270, 40));

        QuantityDW.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        QuantityDW.setForeground(new java.awt.Color(0, 138, 188));
        QuantityDW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinkingwater.add(QuantityDW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 270, 40));

        ChangePaymentCard3.setText("jLabel3");
        ChangePaymentCard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePaymentCard3MouseClicked(evt);
            }
        });
        Drinkingwater.add(ChangePaymentCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 290, 50));

        Donebutton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Donebutton3MouseClicked(evt);
            }
        });
        Drinkingwater.add(Donebutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 130, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Drinking Water view (1).png"))); // NOI18N
        Drinkingwater.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        jTabbedPane1.addTab("tab1", Drinkingwater);

        Internet.setBackground(new java.awt.Color(217, 217, 217));
        Internet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountNameNET.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AccountNameNET.setForeground(new java.awt.Color(0, 138, 188));
        AccountNameNET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Internet.add(AccountNameNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 270, 40));

        CardHolderNET.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CardHolderNET.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderNET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Internet.add(CardHolderNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 270, 40));

        PanNET.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PanNET.setForeground(new java.awt.Color(0, 138, 188));
        PanNET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Internet.add(PanNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 270, 40));

        ExpirationDateNET.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ExpirationDateNET.setForeground(new java.awt.Color(0, 138, 188));
        ExpirationDateNET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Internet.add(ExpirationDateNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 270, 40));

        CompanyNameNET.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CompanyNameNET.setForeground(new java.awt.Color(0, 138, 188));
        CompanyNameNET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Internet.add(CompanyNameNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 270, 40));

        TelephoneNumbNET.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TelephoneNumbNET.setForeground(new java.awt.Color(0, 138, 188));
        TelephoneNumbNET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Internet.add(TelephoneNumbNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 270, 40));

        ChangePaymentCard4.setText("jLabel3");
        ChangePaymentCard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePaymentCard4MouseClicked(evt);
            }
        });
        Internet.add(ChangePaymentCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 290, 50));

        Donebutton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Donebutton4MouseClicked(evt);
            }
        });
        Internet.add(Donebutton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 120, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/internet view (1).png"))); // NOI18N
        Internet.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        jTabbedPane1.addTab("tab1", Internet);

        Telephone.setBackground(new java.awt.Color(217, 217, 217));
        Telephone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountNameTEL.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AccountNameTEL.setForeground(new java.awt.Color(0, 138, 188));
        AccountNameTEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telephone.add(AccountNameTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 270, 40));

        CardHolderTEL.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CardHolderTEL.setForeground(new java.awt.Color(0, 138, 188));
        CardHolderTEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telephone.add(CardHolderTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 270, 40));

        PanTEL.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        PanTEL.setForeground(new java.awt.Color(0, 138, 188));
        PanTEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telephone.add(PanTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 270, 40));

        ExpirationDateTEL.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ExpirationDateTEL.setForeground(new java.awt.Color(0, 138, 188));
        ExpirationDateTEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telephone.add(ExpirationDateTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 270, 40));

        CompanyNameTEL.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CompanyNameTEL.setForeground(new java.awt.Color(0, 138, 188));
        CompanyNameTEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telephone.add(CompanyNameTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 270, 40));

        TelephoneNumbTEL.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TelephoneNumbTEL.setForeground(new java.awt.Color(0, 138, 188));
        TelephoneNumbTEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telephone.add(TelephoneNumbTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 270, 40));

        ChangePaymentCard5.setText("jLabel3");
        ChangePaymentCard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePaymentCard5MouseClicked(evt);
            }
        });
        Telephone.add(ChangePaymentCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 290, 50));

        Donebutton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Donebutton5MouseClicked(evt);
            }
        });
        Telephone.add(Donebutton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 120, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Telephone view (1).png"))); // NOI18N
        Telephone.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        jTabbedPane1.addTab("tab1", Telephone);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DonebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonebuttonMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_DonebuttonMouseClicked

    private void Donebutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Donebutton1MouseClicked
        // TODO add your handling code here:
                dispose();

    }//GEN-LAST:event_Donebutton1MouseClicked

    private void Donebutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Donebutton2MouseClicked
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_Donebutton2MouseClicked

    private void Donebutton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Donebutton3MouseClicked
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_Donebutton3MouseClicked

    private void Donebutton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Donebutton4MouseClicked
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_Donebutton4MouseClicked

    private void Donebutton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Donebutton5MouseClicked
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_Donebutton5MouseClicked

    private void ChangePaymentCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePaymentCardMouseClicked
        CreditCardCustomer frame = new CreditCardCustomer();
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePaymentCardMouseClicked

    private void ChangePaymentCard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePaymentCard1MouseClicked
        CreditCardCustomer frame = new CreditCardCustomer();
        frame.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_ChangePaymentCard1MouseClicked

    private void ChangePaymentCard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePaymentCard2MouseClicked
        CreditCardCustomer frame = new CreditCardCustomer();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePaymentCard2MouseClicked

    private void ChangePaymentCard3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePaymentCard3MouseClicked
       CreditCardCustomer frame = new CreditCardCustomer();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePaymentCard3MouseClicked

    private void ChangePaymentCard4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePaymentCard4MouseClicked
        CreditCardCustomer frame = new CreditCardCustomer();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePaymentCard4MouseClicked

    private void ChangePaymentCard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePaymentCard5MouseClicked
        CreditCardCustomer frame = new CreditCardCustomer();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePaymentCard5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try{
                        UIManager.setLookAndFeel(new FlatDarkLaf());

            }
        catch (Exception ex) {
            java.util.logging.Logger.getLogger(ViewCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameDW;
    private javax.swing.JLabel AccountNameMO;
    private javax.swing.JLabel AccountNameNET;
    private javax.swing.JLabel AccountNameTEL;
    private javax.swing.JLabel AccountNamedGas;
    private javax.swing.JLabel AccountNamedW;
    private javax.swing.JLabel CardHolderDW;
    private javax.swing.JLabel CardHolderGas;
    private javax.swing.JLabel CardHolderMO;
    private javax.swing.JLabel CardHolderNET;
    private javax.swing.JLabel CardHolderTEL;
    private javax.swing.JLabel CardHolderW;
    private javax.swing.JLabel ChangePaymentCard;
    private javax.swing.JLabel ChangePaymentCard1;
    private javax.swing.JLabel ChangePaymentCard2;
    private javax.swing.JLabel ChangePaymentCard3;
    private javax.swing.JLabel ChangePaymentCard4;
    private javax.swing.JLabel ChangePaymentCard5;
    private javax.swing.JLabel CompanyNameDW;
    private javax.swing.JLabel CompanyNameGas;
    private javax.swing.JLabel CompanyNameMO;
    private javax.swing.JLabel CompanyNameNET;
    private javax.swing.JLabel CompanyNameTEL;
    private javax.swing.JLabel CompanyNameW;
    private javax.swing.JLabel CounterCodeW;
    private javax.swing.JLabel CounterCodegas;
    private javax.swing.JLabel Donebutton;
    private javax.swing.JLabel Donebutton1;
    private javax.swing.JLabel Donebutton2;
    private javax.swing.JLabel Donebutton3;
    private javax.swing.JLabel Donebutton4;
    private javax.swing.JLabel Donebutton5;
    private javax.swing.JPanel Drinkingwater;
    private javax.swing.JLabel ExpirationDateDW;
    private javax.swing.JLabel ExpirationDateGas;
    private javax.swing.JLabel ExpirationDateMO;
    private javax.swing.JLabel ExpirationDateNET;
    private javax.swing.JLabel ExpirationDateTEL;
    private javax.swing.JLabel ExpirationDateW;
    private javax.swing.JPanel Gasview;
    private javax.swing.JPanel Internet;
    private javax.swing.JPanel MobileView;
    private javax.swing.JLabel PanDW;
    private javax.swing.JLabel PanGas;
    private javax.swing.JLabel PanNET;
    private javax.swing.JLabel PanTEL;
    private javax.swing.JLabel PanTEMO;
    private javax.swing.JLabel PanW;
    private javax.swing.JLabel PaymentCodeGas;
    private javax.swing.JLabel PaymentCodeW;
    private javax.swing.JLabel QuantityDW;
    private javax.swing.JLabel ServiceProvoiderMO;
    private javax.swing.JPanel Telephone;
    private javax.swing.JLabel TelephoneNumbMO;
    private javax.swing.JLabel TelephoneNumbNET;
    private javax.swing.JLabel TelephoneNumbTEL;
    private javax.swing.JPanel Waterview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
