/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills_management_system;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;

/**
 *
 * @author mariam
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jProgressBar = new javax.swing.JProgressBar();
        percentage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar.setForeground(new java.awt.Color(0, 176, 239));
        jProgressBar.setBorder(null);
        jProgressBar.setMaximumSize(new java.awt.Dimension(310, 14));
        jProgressBar.setMinimumSize(new java.awt.Dimension(310, 14));
        jProgressBar.setPreferredSize(new java.awt.Dimension(310, 14));
        jPanel.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 320, -1, -1));

        percentage.setBackground(new java.awt.Color(109, 177, 147));
        percentage.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        percentage.setForeground(new java.awt.Color(0, 176, 239));
        percentage.setText("%");
        jPanel.add(percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figma_design/Welcome page.png"))); // NOI18N
        jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        try{
                        UIManager.setLookAndFeel(new FlatDarkLaf());

            }
        catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        
        /* Create and display the form */
        WelcomeFrame Page = new WelcomeFrame();
       Page.setVisible(true);
       try{
           for (int i = 0; i<=100; i++){
               Thread.sleep(90);
               Page.jProgressBar.setValue(i);
               Page.percentage.setText(Integer.toString(i)+ "%");
           };
       }
       catch(Exception e){
           System.out.print(e);
       }
       new Login().setVisible(true);
       Page.dispose();
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JLabel percentage;
    // End of variables declaration//GEN-END:variables
}
